apiVersion: valhalla.itayankri/v1alpha1
kind: Valhalla
metadata:
  name: example
spec:
  pbfUrl: https://download.geofabrik.de/europe/andorra-latest.osm.pbf
  minReplicas: 2
  maxReplicas: 5
  resources:
    requests:
      cpu: "2000m"
      memory: "6Gi"
    limits:
      cpu: "1500m"
      memory: "150Mi"
  persistence:
    storage: "2Gi"
    storageClassName: standard-rwx
    accessMode: ReadWriteMany
  service:
    type: LoadBalancer
    annotations:
      example-annotation: "example-annotation"
  predictedTraffic:
    url: https://example.com
    schedule: "*/3 * * * *"
