apiVersion: valhalla.itayankri/v1alpha1
kind: Valhalla
metadata:
  name: example
spec:
  pbfUrl: https://download.geofabrik.de/europe/andorra-latest.osm.pbf
  minReplicas: 1
  maxReplicas: 1
  resources:
    requests:
      cpu: "2000m"
      memory: "2Gi"
    limits:
      cpu: "2"
      memory: "3Gi"
  persistence:
    storage: "2Gi"
    storageClassName: standard
    accessMode: ReadWriteOnce
  service:
    type: LoadBalancer
    annotations:
      example-annotation: "example-annotation"
  predictedTraffic:
    url: https://example.com
    schedule: "*/3 * * * *"
